services:
  postgres:
    image: postgres:latest
    container_name: postgresPG
    environment:
      - POSTGRES_DB=messagesdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5439:5432"
    volumes:
      - postgrespg-data:/var/lib/postgresql/data

volumes:
  postgrespg-data:
